# Generated by Django 3.2.7 on 2021-09-26 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pensum',
            name='state',
        ),
        migrations.RemoveField(
            model_name='program',
            name='state',
        ),
        migrations.AddField(
            model_name='pensum',
            name='file_pdf',
            field=models.FileField(null=True, upload_to='file-pdf-pensum'),
        ),
        migrations.AddField(
            model_name='pensum',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='program',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
