# Generated by Django 3.2.7 on 2021-09-26 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0002_auto_20210926_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pensum',
            name='file_pdf',
            field=models.ImageField(null=True, upload_to='file-pdf-pensum'),
        ),
    ]
