# Generated by Django 3.2.7 on 2021-09-27 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0003_alter_pensum_file_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pensum',
            name='file_pdf',
            field=models.FileField(null=True, upload_to='file-pdf-pensum'),
        ),
    ]
