# Generated by Django 3.0.7 on 2021-09-28 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0004_alter_pensum_file_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pensum',
            name='file_pdf',
            field=models.FileField(upload_to='pensum/%y/%m/%d'),
        ),
    ]
