# Generated by Django 3.2.7 on 2021-09-28 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0005_auto_20210928_0224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pensum',
            name='file_pdf',
            field=models.FileField(upload_to='pensum'),
        ),
    ]
