# Generated by Django 3.2.7 on 2021-09-28 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210928_1108'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('code', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.EmailField(max_length=254, unique=True, verbose_name='Correo electronico')),
                ('password', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'Usuario',
            },
        ),
        migrations.RemoveField(
            model_name='employee',
            name='program_code',
        ),
        migrations.AlterField(
            model_name='employee',
            name='Photo',
            field=models.ImageField(default='pictures/default.jpg', max_length=255, upload_to='pictures'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='code',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='role',
            name='code',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='usuario',
            name='Employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.employee'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='Role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.role'),
        ),
    ]
