# Generated by Django 3.2.7 on 2021-09-28 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0006_alter_pensum_file_pdf'),
        ('user', '0003_auto_20210928_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='program_code',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='proyecto.program'),
        ),
    ]
